version: "3.7"
services:
  api:
    build:
      context: ./api
      target: development
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.prod
    restart: unless-stopped
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - api
  #   command: npm start
