# Generated by Django 3.0.8 on 2020-08-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('winscore', models.IntegerField(default=3)),
                ('drawscore', models.IntegerField(default=1)),
                ('losescore', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(blank=True, default=3, null=True)),
                ('max_round_duration', models.DurationField(blank=True, default=3600, null=True)),
                ('tournament_players', models.ManyToManyField(related_name='_tournament_tournament_players_+', to='tournament.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_round', models.IntegerField(default=1)),
                ('duration', models.DurationField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('pod_players', models.ManyToManyField(related_name='_pod_pod_players_+', to='tournament.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_winner', to='tournament.Player')),
            ],
        ),
    ]
