# Generated by Django 3.0.8 on 2020-10-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20201005_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='standing',
            new_name='score',
        ),
    ]
