# Generated by Django 3.0.8 on 2020-10-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20201007_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Participant'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='pod_players',
            field=models.ManyToManyField(through='tournament.Player', to='tournament.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('pod', 'participant')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='person',
        ),
    ]
