# Generated by Django 3.0.8 on 2020-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20201007_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_pod_players',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_pod_players',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
