# Generated by Django 3.0.8 on 2020-10-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_pod_pod_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pod_player', to='tournament.Participant'),
        ),
    ]
