# Generated by Django 3.0.8 on 2020-10-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20201007_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
