# Generated by Django 3.0.8 on 2020-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20201012_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='_round',
            field=models.IntegerField(default=1),
        ),
    ]
