# Generated by Django 3.0.8 on 2020-10-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_pod__round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pod',
            old_name='_round',
            new_name='round_nr',
        ),
    ]
