# Generated by Django 3.0.8 on 2020-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_tournament_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ogw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='omw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
