# Generated by Django 3.0.8 on 2020-11-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20201123_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='omw',
        ),
    ]
